import { Request, Response } from "express";
import { AuthRequest } from "../middleware/middleware";
export declare const BootstrapAdmin: (req: Request, res: Response) => Promise<void>;
export declare const RegisterUser: (req: Request, res: Response) => Promise<void>;
export declare const RegisterTutor: (req: AuthRequest, res: Response) => Promise<void>;
export declare const LoginUser: (req: Request, res: Response) => Promise<void>;
export declare const LogoutUser: (req: AuthRequest, res: Response) => void;
export declare const AdminForgotPassword: (req: Request, res: Response) => Promise<void>;
export declare const AdminVerifyForgotPasswordOtp: (req: Request, res: Response) => Promise<void>;
export declare const AdminResetPassword: (req: Request, res: Response) => Promise<void>;
export declare const GetCurrentUser: (req: AuthRequest, res: Response) => Promise<void>;
export declare const UpdateProfile: (req: AuthRequest, res: Response) => Promise<void>;
export declare const ChangePassword: (req: AuthRequest, res: Response) => Promise<void>;
